apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: mapid-infisical-auth
spec:
  infisicalConnectionRef:
    name: mapid-infisical-connection
    namespace: default
  method: universal
  universal:
    clientIdRef:
      name: universal-auth-credentials
      namespace: default
      key: clientId
    clientSecretRef:
      name: universal-auth-credentials
      namespace: default
      key: clientSecret
