apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: mapid-static-secret
spec:
  infisicalAuthRef:
    name: mapid-infisical-auth
    namespace: default
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectSlug: node-js
      environmentSlug: prod
      secretPath: /
    - projectSlug: bun-js-h-gzy
      environmentSlug: prod
      secretPath: /
    - projectSlug: node-js-refactoring-is-lo
      environmentSlug: prod
      secretPath: /
  targets:
    - name: new-geoserver-nodejs-infisical-secret
      namespace: default
      kind: Secret
      creationPolicy: Owner
    - name: new-geoserver-bunjs-infisical-secret
      namespace: default
      kind: Secret
      creationPolicy: Owner
    - name: new-geoserver-nodejs-rf-infisical-secret
      namespace: default
      kind: Secret
      creationPolicy: Owner
